import Link from "next/link";
import "./globals.css";
import { HomeIcon } from "@heroicons/react/24/solid";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-purple-600 text-white p-5 flex items-baseline justify-between">
          <h1>React Tutorials</h1>
          <Link href="/">
            <HomeIcon className="h-6 w-6" />
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
